### ISSUE TITLE
Custom rendering doesn't work in some setups

### ISSUE THREAD

**Issue by lukefromdc** [ammen99/wayfire#3] opened 2018-03-24 02:55 UTC
I don't know if its just my .ini file but on my setup on Debian Unstable and AMD r600g drivers I have not been able to get the desktop cube or expo to show by setting any keybinding as "activate."

EDIT: nothing brings them up with the default, unmodified .ini file either

**Comment by ammen99** [comment] 2018-03-24 05:45
Does animate plugin work(provides animation when a window is opened/closed)? Or you see a flicker(gray screen instead of animation) when you open an app? If this is the case, then the whole custom rendering is to blame.

**Comment by lukefromdc** [comment] 2018-03-24 05:46
I get a flicker on opening or closing any and all windows

**Comment by ammen99** [comment] 2018-03-24 09:15
@lukefromdc  Will you be able to help me debug it (possibly later)? If yes, then PM me in gitter when you've got some time to spare, because on my 2 laptops I haven't been able to reproduce the issue.

**Comment by lukefromdc** [comment] 2018-03-24 22:42
I can certainly test any changes, but don't know enough about the Wayland code or OpenGL to write much for this yet

**Comment by lukefromdc** [comment] 2018-03-24 22:43
Wonder if this is a hardware/OpenGL issue? I am on radeon/r600g open source drivers on a Radeon HD6750 graphics card, and your laptop is probably something different.

**Comment by ammen99** [comment] 2018-03-25 04:59
well, it most likely is graphics. I made a guess at what was wrong, can you test the debug branch?

**Comment by lukefromdc** [comment] 2018-03-25 18:38
The only thing I got in the logs was output from Caja (relating to the Xwayland desktop) even on a debug build. Confirm though that disabling animation stops the flickers

**Comment by ammen99** [comment] 2018-03-25 19:27
The missing output from the logfile is strange. Are you sure you installed wayfire at the correct location(e.g when you compiled first you installed in /usr/bin, but the second time with debug in /usr/local/bin)? Otherwise you should get at least some output from libweston in the logfile.

**Comment by lukefromdc** [comment] 2018-03-25 19:34
Confirm, installation is in /usr/bin and no sign of anything from wayfire in /usr/local/bin. With no make uninstall target, what is installed stays in the filesystem unless manually removed or installed by building a debian package and then removed. I did get some output from Caja when run with --force-desktop from within wayfire, just no output from wayfire itself, and no debugging looking output on the console either

**Comment by ammen99** [comment] 2018-03-26 08:17
Hi, I finally managed to reproduce the bug on my friend's laptop. Please test the newest commit in the debug branch. Also don't forget to pull latest commits from patched libweston repo.

**Comment by lukefromdc** [comment] 2018-03-26 22:51
I can confirm the latest changes fix animation in and only in the debug branch. No more flicker, windows open in zoom mode as now configured

**Comment by lukefromdc** [comment] 2018-03-26 23:02
Cube works, tile works, shortcuts are enough different from compiz to be a bit counter-intuitive. I have yet to figure out how to activage expo, but with the debug branch the main issue (might be limited to debug) is sometimes getting a rendering/redraw issue in Xwayland windows that have been tiled.

**Comment by ammen99** [comment] 2018-03-27 05:50
Which tiling do you use (tile or grid plugin)? For grid you can change them the way you want, but tile is still in progress.

About expo: did you set a keybinding in the [expo] section (activate=<super> KEY_E is the default)? It seems I forgot to include it in the default config.

The redraw issue: what does that mean?  Bad pixels? The window doesn't update? When is it happening(in grid, tile? while resizing? or after they've been configured)?

**Comment by lukefromdc** [comment] 2018-03-27 05:56
Redraw issue was many old partial copies overlapping of an Xwayland window that had been tiled and then moved, did not happen all the time.  Keybindings I tried for Expo before did not work, will test that some more.  Not sure whether grid or tile was in use, but was able to pull windows to edge to tile them.  The ini file is only slightly modified

**Comment by ammen99** [comment] 2018-03-27 05:59
The redraw issue seems like a background/panel crash. Can you send a screenshot(super+S  and it it saved in ~/Pictures)

**Comment by lukefromdc** [comment] 2018-03-27 06:01
This section in the .ini file for expo generated no results:

```
# show a live preview of all workspaces on the current output, can also move the windows on them
[expo]
duration = 300
offset = 0
background = 0.1 0.1 0.1 1.0
activate = <ctrl> <alt> right

```

**Comment by ammen99** [comment] 2018-03-27 06:03
mm, expo can only be activated with a keybinding for now

**Comment by lukefromdc** [comment] 2018-03-27 06:04
Could not duplicate background issue right now, maybe something else had to crash first?

**Comment by ammen99** [comment] 2018-03-27 06:05
Yes, I think that the trailing issue is like what you could get in Windows XP, and that is because background+shell crashed. Another item in TODO: split background and panel

**Comment by lukefromdc** [comment] 2018-03-27 06:06
activate = <ctrl> <alt> KEY_RIGHT did not work either for expo

**Comment by ammen99** [comment] 2018-03-27 06:08
Just pull the debug branch again and try(no need for libweston)

**Comment by lukefromdc** [comment] 2018-03-27 06:12
That works, I did not know expo had a different name for activation. Very smooth and nice running, this is still the debug branch of course.

**Comment by ammen99** [comment] 2018-03-27 06:15
I didn't know it also :P Glad to hear it works, what resolution do you use? Because I spent some time optimizing Expo, and now it works on my 1920x1080, but I wonder if my optimizations are enough for 4K?

**Comment by ammen99** [comment] 2018-03-27 06:16
Something that came to my mind: If panel crashes relatively often, then you can try running it under gdb to be able to get a backtrace when it crashes.

**Comment by lukefromdc** [comment] 2018-03-27 18:25
I normally have two monitors available: a 1080X1920 and a smaller 1024X768 that is normally turned off when not in use, but in a Wayland session both come up. I get a separate cube or expo for each screen, the active screen (last one clicked with the mouse) being the one the effect is applied to.

I don't own any 4K hardware at all

**Comment by ammen99** [comment] 2018-03-27 19:13
Anyway, it seems that this issue has been resolved, I'll close it. If you encounter crash from panel again, please open another issue.

**Closed by ammen99** 2018-03-27 19:13 UTC

**Comment by lukefromdc** [comment] 2018-03-27 19:14
Has the fix been moved to master from the debug branch?

**Comment by ammen99** [comment] 2018-03-27 19:31
Yes, I merged it a little while ago.

**Comment by lukefromdc** [comment] 2018-03-27 19:38
I just retested master, animation and expo worked, but cube turned the screen dark gray. Debug is still the branch that fully works here, so master needs at least one more commit from it

**Comment by ammen99** [comment] 2018-03-27 19:57
Are you compiling with -DUSE_GLES32=True or False?

**Comment by lukefromdc** [comment] 2018-03-27 20:02
I am just copying the whole
cmake ../ -DCMAKE_BUILD_TYPE=Release -DUSE_GLES32=True -DCMAKE_INSTALL_PREFIX=/usr
line from the README as I had issues trying to build from cmake-gui. Is that the issue perhaps?

**Comment by ammen99** [comment] 2018-03-27 20:05
It might be worth to try to get some logs now, as you weren't able to do so before. Try this command for cmake:

`cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DUSE_GLES32=True`

Then compile, install and try to gather logs: `wayfire log.txt`. The log is generated in the current directory. Please try this and tell me if you still don't get a log.

**Comment by lukefromdc** [comment] 2018-03-27 20:11
All I got in the log was this from Caja:
Initializing caja-xattr-tags extension
Initializing caja-image-converter extension
Initializing caja-open-terminal extension

**Comment by lukefromdc** [comment] 2018-03-27 20:13
Just found out that a build from master with
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DUSE_GLES32=FALSE
works fine for the cube too.. Looks like I have an issue with GLES on my setup

**Comment by ammen99** [comment] 2018-03-27 20:14
Perhaps some shader doesn't compile. That's why I wanted to see a log, which we unfortunately cannot get yet. Are you sure you have write permissions for the current directory? That nothing else is overwriting the file?

**Comment by ammen99** [comment] 2018-03-27 20:16
Also do you try to give wayfire any other options(it doesn't support anything else that a log as the first option)?

**Comment by lukefromdc** [comment] 2018-03-27 20:24
No, it was just wayfire > /home/luke/Desktop/wayfire.log and this suppressed output to terminal, diverted the Caja text to a logfile, but no log output from wayland itself.

**Comment by lukefromdc** [comment] 2018-03-27 20:25
Some of this stuff I really cannot be sure about, though I build in the user directory as user and don't see permission problems there in general.

**Comment by ammen99** [comment] 2018-03-27 20:26
No, no, give the log file as an argument, not as redirect :D just copy and paste this:

`wayfire log.txt`

NOT `wayfire > log.txt`

It is a bit stupid and I'll change it sometime

**Comment by lukefromdc** [comment] 2018-03-27 20:28
That works, now for your experiment, then I am out of time for now

**Comment by ammen99** [comment] 2018-03-27 20:29
OK, I didn't quite understand you, but when you have time, please send me a log with `-DUSE_GLES32=True` after you try cube.

**Comment by lukefromdc** [comment] 2018-03-27 20:31
This log resulted with gles and the failed cube

[wayfire.log.gz](https://github.com/ammen99/wayfire/files/1853698/wayfire.log.gz)

**Comment by lukefromdc** [comment] 2018-03-27 20:32
That is the log you should have now

**Comment by ammen99** [comment] 2018-03-27 20:34
The problem is simply that you do not have support for GLES 3.2 in driver and should compile with
 `-DUSE_GLES32=False` :D Thanks for testing though

**Comment by lukefromdc** [comment] 2018-03-27 20:43
You are welcome, now I know how to build this and you know what not to worry about
